version: '3'

services:
    taucetistation:
        build:
            context: .
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
             - ./local.settings.php:/var/www/src/local.settings.php
             - ./storage:/var/www/storage
